name: Build & Deploy to Pages repo

on:
  workflow_run:
    workflows: ["e2e"]
    types: [completed]

jobs:
  build-deploy:
    if: >
        ${{
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' &&
          github.event.workflow_run.repository.full_name == github.repository
        }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-out
          path: out
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanity check artifact
        run: ls -la out && test -f out/index.html

      - name: Deploy to external Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: DaiYuzeng/daiyuzeng.github.io
          publish_branch: main
          publish_dir: ./out
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy from portfolio@${{ github.event.workflow_run.head_sha }}"
