name: E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'yarn' }
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx playwright install --with-deps
      - run: yarn test:e2e
